[build]
  command = "npm install --legacy-peer-deps && npm run build"


# Optional: Environment variables, redirects, etc.
[build.environment]
  NODE_VERSION = "17"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
